function XR_plot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 05-May-2016 18:31:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create xlabel
xlabel('EAST [m]');

% Create ylabel
ylabel('NORTH [m]');

