function XR_plot_3D(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 05-May-2016 18:30:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create xlabel
xlabel('EAST [m]');

% Create ylabel
ylabel('NORTH [m]');

% Create zlabel
zlabel('h [m]');

